import { useState } from "react";
import { Flag, ShieldBan } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

export function AccountSafetyDialog({ open, onOpenChange, userId, username, blocked, onChanged }: { open:boolean;onOpenChange:(open:boolean)=>void;userId:number;username:string;blocked:boolean;onChanged:()=>void }){
  const [view,setView]=useState<"menu"|"report">("menu");const [category,setCategory]=useState("harassment");const [details,setDetails]=useState("");const [busy,setBusy]=useState(false);
  const block=async()=>{if(!blocked&&!window.confirm(`Block @${username}? You will unfollow each other and direct messaging will stop.`))return;setBusy(true);try{await api(`/safety/blocks/${userId}`,{method:blocked?"DELETE":"POST"});toast.success(blocked?"Account unblocked":"Account blocked");onChanged();onOpenChange(false);}catch(err){toast.error(err instanceof Error?err.message:"Unable to update block");}finally{setBusy(false);}};
  const report=async()=>{setBusy(true);try{await api("/safety/reports",{method:"POST",body:JSON.stringify({targetType:"user",targetId:String(userId),reportedUserId:userId,category,details})});toast.success("Report submitted privately");setDetails("");setView("menu");onOpenChange(false);}catch(err){toast.error(err instanceof Error?err.message:"Unable to report");}finally{setBusy(false);}};
  return <Dialog open={open} onOpenChange={(next)=>{onOpenChange(next);if(!next)setView("menu");}}><DialogContent><DialogHeader><DialogTitle>{view==="menu"?`Safety options for @${username}`:"Submit a private report"}</DialogTitle><DialogDescription>{view==="menu"?"Reports go to platform administrators. Blocking changes your personal experience immediately.":"Give moderators enough detail to understand what happened. The reported member will not see your report."}</DialogDescription></DialogHeader>{view==="menu"?<div className="grid gap-2"><Button variant="outline" className="h-auto justify-start p-4 text-left" onClick={()=>setView("report")}><Flag className="mr-3 h-5 w-5 text-amber-600"/><span><span className="block font-semibold">Report @{username}</span><span className="mt-0.5 block text-xs font-normal text-slate-500">Flag harassment, spam, scams, or another violation.</span></span></Button><Button variant="outline" className="h-auto justify-start border-red-200 p-4 text-left text-red-700" disabled={busy} onClick={()=>void block()}><ShieldBan className="mr-3 h-5 w-5"/><span><span className="block font-semibold">{blocked?"Unblock":"Block"} @{username}</span><span className="mt-0.5 block text-xs font-normal text-red-600/70">{blocked?"Allow follows and direct messages again.":"Remove follows and prevent direct messages."}</span></span></Button></div>:<div className="space-y-4"><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="harassment">Harassment or threats</SelectItem><SelectItem value="spam">Spam</SelectItem><SelectItem value="scam">Scam or fraud</SelectItem><SelectItem value="hate">Hateful conduct</SelectItem><SelectItem value="impersonation">Impersonation</SelectItem><SelectItem value="privacy">Private information</SelectItem><SelectItem value="underage">Underage user</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select><Textarea rows={6} minLength={10} maxLength={2000} placeholder="What happened? Include where it occurred and any relevant context." value={details} onChange={e=>setDetails(e.target.value)}/><div className="flex justify-between gap-2"><Button variant="ghost" onClick={()=>setView("menu")}>Back</Button><Button disabled={busy||details.trim().length<10} onClick={()=>void report()}>{busy?"Submitting…":"Submit report"}</Button></div></div>}</DialogContent></Dialog>;
}
