import { useState } from "react";
import { Link, useLocation } from "wouter";
import { CheckCircle2, KeyRound, Mail } from "lucide-react";
import { api } from "@/lib/api";
import { PublicPage } from "@/components/public/PublicChrome";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

export function ForgotPassword() {
  const [email,setEmail]=useState(""); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{await api("/auth/forgot-password",{method:"POST",body:JSON.stringify({email})});setDone(true);}catch(err){setError(err instanceof Error?err.message:"Unable to continue");}finally{setBusy(false);}};
  return <PublicPage><main className="mx-auto max-w-md px-5 py-16"><div className="rounded-2xl border bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><Mail className="h-5 w-5"/></span><h1 className="mt-5 text-2xl font-black">Recover your account</h1>{done?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><CheckCircle2 className="h-5 w-5 text-emerald-600"/><p className="mt-2 text-sm font-semibold text-emerald-950">Check your inbox if the address matches an account.</p><p className="mt-1 text-xs leading-5 text-emerald-800">The one-time link expires in 30 minutes. Check spam too.</p></div>:<><p className="mt-2 text-sm leading-6 text-slate-600">Enter your account email. For privacy, the response is the same whether an account exists or not.</p><form onSubmit={submit} className="mt-6 space-y-4"><div><Label htmlFor="recovery-email">Email</Label><Input id="recovery-email" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required/></div>{error&&<p className="text-sm text-red-600">{error}</p>}<Button className="w-full" disabled={busy}>{busy?"Sending…":"Send secure reset link"}</Button></form></>}<Link href="/login" className="mt-5 block text-center text-sm font-semibold text-blue-600">Back to login</Link></div></main></PublicPage>;
}

export function ResetPassword() {
  const [,navigate]=useLocation(); const token=new URLSearchParams(window.location.search).get("token")??""; const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");if(password!==confirm)return setError("Passwords do not match.");setBusy(true);try{await api("/auth/reset-password",{method:"POST",body:JSON.stringify({token,password})});setDone(true);setTimeout(()=>navigate("/login"),1800);}catch(err){setError(err instanceof Error?err.message:"Unable to reset password");}finally{setBusy(false);}};
  return <PublicPage><main className="mx-auto max-w-md px-5 py-16"><div className="rounded-2xl border bg-white p-6 shadow-sm"><span className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-blue-600"><KeyRound className="h-5 w-5"/></span><h1 className="mt-5 text-2xl font-black">Choose a new password</h1>{done?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-900">Password updated. Redirecting to login…</div>:<><p className="mt-2 text-sm text-slate-600">Use 10–128 characters with at least one letter and number. All existing sessions will be signed out.</p><form onSubmit={submit} className="mt-6 space-y-4"><div><Label>New password</Label><Input type="password" autoComplete="new-password" minLength={10} value={password} onChange={e=>setPassword(e.target.value)} required/></div><div><Label>Confirm password</Label><Input type="password" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} required/></div>{!token&&<p className="text-sm text-red-600">This reset link is missing its secure token.</p>}{error&&<p className="text-sm text-red-600">{error}</p>}<Button className="w-full" disabled={busy||!token}>{busy?"Updating…":"Update password"}</Button></form></>}</div></main></PublicPage>;
}
