import { Link, useParams } from "wouter";
import { AlertTriangle, Scale, ShieldCheck, Users } from "lucide-react";
import { PublicPage } from "@/components/public/PublicChrome";

type LegalSection = { title: string; body: string[] };

const policies: Record<string, { title: string; eyebrow: string; icon: typeof Scale; intro: string; sections: LegalSection[] }> = {
  privacy: {
    title: "Privacy Policy", eyebrow: "Your data, in plain language", icon: ShieldCheck,
    intro: "This policy explains what BettorSuite collects, why we use it, when it may be shared, and the choices you have. It applies to our website, account services, betting journal, mock betting tools, profiles, groups, messaging, and community features.",
    sections: [
      { title: "Information we collect", body: ["Account information: email address, username, password hash, display name, biography, profile photo, favorite sport, legal-age confirmation, and policy acceptance timestamps.", "Activity and content: sportsbook journal entries, virtual bets, bankroll and reconciliation history, public picks, daily cards, groups, follows, nicknames, reactions, messages, reports, blocks, and moderation records.", "Technical information: session identifiers, approximate IP address, browser/device information, login timestamps, presence status, usage events, performance measurements, and security logs. We do not intentionally collect precise location, sportsbook credentials, or payment-card information."] },
      { title: "How we use information", body: ["We use information to operate and secure accounts; calculate and display tracking statistics; deliver social, messaging, and moderation features; prevent fraud and abuse; recover accounts; respond to requests; analyze reliability and performance; and comply with legal obligations.", "Public profile fields, public tracked picks, leaderboard statistics, Daily Cards, and content posted to the War Room are visible to other signed-in members. Private wallet details, mock bankroll data, direct messages, private nicknames, and security information are not public unless you choose to share content derived from them."] },
      { title: "Legal bases for processing", body: ["Where EEA or UK data-protection law applies, we process account, journal, messaging, and security data because it is necessary to provide the service you request; to pursue legitimate interests such as service security, abuse prevention, support, and product improvement; to comply with law; and, where required, with your consent. You may withdraw consent without affecting earlier lawful processing."] },
      { title: "Service providers and disclosures", body: ["We may use hosting, database, email delivery, analytics, performance monitoring, and security providers to process data on our behalf. Current infrastructure may include Vercel and a managed PostgreSQL provider. These providers may process data in countries different from yours under their own safeguards.", "We may disclose information when reasonably necessary to comply with law, protect users or the service, investigate abuse, enforce our terms, or complete a merger, financing, acquisition, or asset transfer. We do not sell sportsbook journal data. If applicable law defines certain analytics disclosures as a sale or sharing, you may submit an opt-out request."] },
      { title: "Retention and deletion", body: ["We keep account information while your account is active and retain other data only as long as reasonably needed for the purposes described here, security, dispute resolution, and legal compliance. Retention periods vary by data type.", "You can delete your account from your profile. Deletion removes login, profile, betting, wallet, and messaging data from the active service, subject to limited backups, legal holds, fraud-prevention records, and de-identified information. Blocking or deleting content does not guarantee that another user has not already copied it."] },
      { title: "Your rights and choices", body: ["Depending on where you live, you may have rights to access, correct, delete, export, restrict, or object to processing; withdraw consent; opt out of certain sharing or targeted advertising; or appeal a decision. You may also lodge a complaint with your local privacy regulator.", "Use our Privacy Request form to exercise a right. We may verify your identity before completing a request. Authorized agents may submit requests where allowed by law, but we may require proof of authority."] },
      { title: "US state privacy disclosures", body: ["We do not sell personal information and do not use personal information for cross-context behavioral advertising. We use sensitive account credentials and message content only to provide, secure, and moderate the service. The categories collected, purposes, recipients, and retention approach described above also serve as our notice at collection. If these practices change, we will update this policy and provide required choices before the change applies."] },
      { title: "Cookies and analytics", body: ["BettorSuite uses a strictly necessary, HTTP-only session cookie to keep you signed in. We may use privacy-conscious web analytics and performance tools to understand traffic, crashes, and page speed. Browser controls can limit cookies, but disabling the session cookie prevents account access."] },
      { title: "Security, children, and changes", body: ["We use measures designed to protect data, including password hashing, expiring sessions, rate limiting, access controls, and encrypted transport in production. No system is perfectly secure; report suspected compromise immediately and change your password.", "BettorSuite is not directed to children and is limited to people who meet the legal gambling age where they live. We do not knowingly collect personal information from underage users.", "We may update this policy as the service changes. Material changes will be communicated through the service where appropriate. The effective date below identifies the current version."] },
    ],
  },
  terms: {
    title: "Terms of Use", eyebrow: "The rules of the suite", icon: Scale,
    intro: "These Terms govern your access to BettorSuite. By creating an account or using the service, you agree to them and to our Privacy Policy. If you do not agree, do not use BettorSuite.",
    sections: [
      { title: "Eligibility and accounts", body: ["You must be legally able to enter this agreement and meet the legal gambling age in your jurisdiction. You are responsible for accurate registration information, your credentials, and activity under your account. Do not share, sell, or automate access to an account."] },
      { title: "What BettorSuite is—and is not", body: ["BettorSuite is a recordkeeping, simulation, and social community product. It is not a sportsbook, bookmaker, gambling operator, financial adviser, tipster guarantee, or payment service. We do not accept or place wagers and do not guarantee the accuracy of manually entered data, calculated returns, shared picks, or community claims.", "You are solely responsible for complying with local law, sportsbook rules, taxes, and responsible-gambling limits. Never treat simulated performance as a promise of real-world results."] },
      { title: "Acceptable use", body: ["Do not harass or threaten others; impersonate people; promote scams; manipulate tracked results; spam; share unlawful, infringing, hateful, sexually exploitative, or private content; attempt unauthorized access; scrape the service; interfere with security; or use BettorSuite to facilitate illegal gambling or transactions."] },
      { title: "Your content and public activity", body: ["You keep ownership of content you submit. You grant BettorSuite a worldwide, non-exclusive, royalty-free license to host, reproduce, format, display, and distribute that content only as needed to operate, improve, and moderate the service. You represent that you have the rights required to post it.", "Public picks and their tracking record may remain visible until deleted. Edits may be recorded to preserve community integrity. Other users may tail a shared pick into their own private tracker, creating a separate record outside your control."] },
      { title: "Moderation and enforcement", body: ["We may investigate reports, remove content, restrict posting, remove users from groups, suspend access, reset abusive data, or delete accounts when reasonably necessary to protect the service or enforce these Terms. Administrators may access account and content records for support, security, and moderation, with actions recorded in an audit trail."] },
      { title: "Service changes and availability", body: ["The service may change, pause, or end. We may perform maintenance, add limits, or discontinue features. You should keep any records you cannot afford to lose. We do not promise uninterrupted availability or permanent storage."] },
      { title: "Disclaimers and liability", body: ["To the fullest extent allowed by law, BettorSuite is provided “as is” and “as available,” without warranties of accuracy, fitness, non-infringement, availability, or profitability. Betting carries a risk of loss.", "To the fullest extent allowed by law, BettorSuite and its operators are not liable for indirect, incidental, special, consequential, exemplary, or lost-profit damages arising from use of the service, community picks, data loss, or third-party sportsbooks. Some jurisdictions do not allow certain exclusions, so these limits may not fully apply to you."] },
      { title: "Ending use and updates", body: ["You may stop using BettorSuite or delete your account at any time. Provisions that reasonably should survive termination—including ownership, disclaimers, liability limits, and dispute-related terms—continue to apply. We may update these Terms and will identify the current effective date."] },
    ],
  },
  "community-guidelines": {
    title: "Community Guidelines", eyebrow: "Compete hard. Keep it clean.", icon: Users,
    intro: "BettorSuite works when the record matters more than the loudest voice. These rules apply to profiles, the War Room, groups, direct messages, shared slips, and Daily Cards.",
    sections: [
      { title: "Be honest about the record", body: ["Do not fake tickets, manipulate outcomes, misrepresent odds, conceal material edits, or claim guaranteed wins. Clearly distinguish opinions, simulations, and tracked wagers."] },
      { title: "Respect people", body: ["No harassment, threats, stalking, hate speech, sexual exploitation, doxxing, unwanted repeated contact, or attacks based on protected characteristics. Blocking is available for personal boundaries; reports alert moderators to rule violations."] },
      { title: "No scams or illegal activity", body: ["Do not solicit account credentials or payments, operate unapproved paid pick schemes, facilitate illegal wagering, launder money, evade sportsbook rules, advertise deceptive services, or distribute malware and phishing links."] },
      { title: "Keep content useful", body: ["Avoid spam, duplicate promotion, irrelevant bulk messages, graphic content, and intellectual-property infringement. Group owners can set stricter rules for their own spaces, but platform rules always apply."] },
      { title: "Enforcement", body: ["Moderators may remove content, issue posting restrictions, limit group access, preserve evidence, suspend accounts, or permanently remove accounts. Severity, context, history, intent, and risk inform enforcement. Submit a report with specific details when something crosses the line."] },
    ],
  },
  "responsible-gambling": {
    title: "Responsible Gambling", eyebrow: "The best edge is a hard limit", icon: AlertTriangle,
    intro: "BettorSuite tracks and simulates betting activity; it does not accept wagers. Our tools should support awareness—not encourage chasing losses or betting beyond your limits.",
    sections: [
      { title: "Use the suite as a mirror", body: ["Set a bankroll you can afford to lose, define a unit size before betting, review net results over meaningful periods, and treat reconciliation as record correction—not a way to erase losses. Mock Betting can test ideas without risking money."] },
      { title: "Know the warning signs", body: ["Pause if you are chasing losses, hiding activity, borrowing to bet, increasing stakes for excitement, missing obligations, feeling distressed, or unable to follow limits. Profit boosts, parlays, streaks, and community picks do not change the underlying risk."] },
      { title: "Take action", body: ["Use deposit, wager, time, and self-exclusion tools offered by your sportsbook or jurisdiction. Consider blocking betting apps, asking a trusted person for support, and contacting a qualified gambling-support organization. If you are in immediate danger or thinking about self-harm, contact local emergency services now.", "United States: call or text 1-800-GAMBLER where available. Elsewhere, contact your national gambling helpline or regulator for local support. BettorSuite does not provide clinical or financial advice."] },
      { title: "Age and local law", body: ["Do not use BettorSuite if you are under the legal gambling age where you live. Sports betting laws and access vary by location; you are responsible for understanding and following them."] },
    ],
  },
};

export default function LegalPage({ slug: providedSlug }: { slug?: string }) {
  const params = useParams<{ slug: string }>();
  const policy = policies[providedSlug ?? params.slug] ?? policies.privacy;
  const Icon = policy.icon;
  return <PublicPage><main className="mx-auto max-w-4xl px-5 py-14 lg:px-8"><div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-10"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-blue-600"><Icon className="h-4 w-4" />{policy.eyebrow}</div><h1 className="mt-3 text-4xl font-black tracking-tight text-slate-950">{policy.title}</h1><p className="mt-2 text-xs text-slate-500">Effective August 15, 2026</p><p className="mt-6 text-base leading-7 text-slate-700">{policy.intro}</p><div className="mt-9 space-y-9">{policy.sections.map((section)=><section key={section.title}><h2 className="text-xl font-bold text-slate-950">{section.title}</h2><div className="mt-3 space-y-3">{section.body.map((paragraph)=><p key={paragraph} className="text-sm leading-7 text-slate-600">{paragraph}</p>)}</div></section>)}</div><div className="mt-10 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm text-blue-950">Questions, privacy rights, or safety concerns? <Link href="/privacy-request" className="font-bold text-blue-700 underline underline-offset-2">Submit a private request</Link>.</div></div></main></PublicPage>;
}
